name: make

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'

      - run: make dist/sqlc-gen-python-orm.wasm
      - run: make dist/sqlc-gen-python-orm.wasm

      - run: |
          SHA256=$(cat dist/sqlc-gen-python-orm.wasm.sha256)
          cat > release.md <<- EOF
          ```
          plugins:
          - name: py
          wasm:
            url: https://github.com/veltiosoft/sqlc-gen-python-orm/releases/download/${GITHUB_REF}/sqlc-gen-python-orm.wasm
            sha256: ${SHA256}
          ```
          EOF

      - name: Upload Github Release
        run: gh release create "${GITHUB_REF}" --notes --notes-file release.md dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
