name: make

on:
  push:
    tags:
      - 'v*'

env:
  GOTOOLCHAIN: local

jobs:
  release:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - run: make dist/sqlc-gen-python-orm.wasm.sha256

      - run: |
          SHA256=$(cat dist/sqlc-gen-python-orm.wasm.sha256)
          URL="https://github.com/veltiosoft/sqlc-gen-python-orm/releases/download/${GITHUB_REF_NAME}/sqlc-gen-python-orm.wasm"
  
          echo '```' | tee -a release.md
          echo "plugins:" | tee -a release.md
          echo "- name: py" | tee -a release.md
          echo "  wasm:" | tee -a release.md
          echo "    url: ${URL}" | tee -a release.md
          echo "    sha256: ${SHA256}" | tee -a release.md
          echo '```' | tee -a release.md


      - name: Upload Github Release
        run: gh release create "${GITHUB_REF}" --notes-file release.md dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
